from setuptools import setup, find_packages


setup(
    name="featureinterp",
    packages=find_packages(),
    version="0.0.1",
    author="Samuel Pfrommer",
    install_requires=[
        "httpx>=0.22",
        "scikit-learn",
        "boostedblob>=0.13.0",
        "tiktoken",
        "blobfile",
        "numpy",
        "pytest",
        "orjson",
        "together",
        "dacite",
        "torch",
        "torchvision",
        "einops",
        "jaxtyping",
        "datasets",
        "transformers",
        "tqdm",
        "wandb",
        "sae_lens",
        "transformer_lens",
        "sentence_transformers",
        "info-nce-pytorch",
        "pdbpp",
        "colorama",
        "bitsandbytes",
        "json-repair",
        "google-generativeai",
    ],
    url="",
    description="",
    python_requires='>=3.9',
)
